name: New dependency report
description: New dependencies are very welcome if they help you forward, we do expect you to perform some checks by using this form to create an issue in your repo. You can close them by mentioning this issue in your implementing PR.
title: "[new-dependency]: "
labels: ["new-dependency"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this report 🤗

      A dependency is something that you include in your code at build time: something like a nuget package. This will help us to improve the quality of new dependencies that we take in.

      Make sure to 'fixate' your dependency version (specify the version or use a https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json): we always want the build to be predictable.

- type: input
  id: website
  attributes:
    label: Website
    description: "Where can you find information about this component"
    placeholder: "Some public nice and shiny website"
  validations:
    required: true

- type: input
  id: repo
  attributes:
    label: Public repository
    description: "Where can you find the source of this library (probably some GitHub repo)"
    placeholder: "https://github.com/ShipitSmarter/vscode-sops-edit"
  validations:
    required: false

- type: textarea
  id: checks
  attributes:
    label: Dependency checks
    description: "Please take some time to analyze the dependency that you are about to add. Not all check marks have to be green: use your common sense. Make sure to include someone in your decision if in doubt."
    value: |
      * General: 
        * [ ] Is the component open source?
        * [ ] Is there a license that allows us to use it? 
        * [ ] Does it use signed commits?
      * Is it of good quality?
        * [ ] Does it have unit tests?
        * [ ] Does it have documentation?
      * Is it maintained?
        * [ ] Do you see more than one contributor?
        * [ ] Does it have recent releases?
      ...
    render: bash
  validations:
    required: true

- type: textarea
  id: additional-information
  attributes:
    label: Additional Information
    description: |
      Provide any additional information that might be useful in the future (not required).
